    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aps;
import static aps.Descriptografia.acerto;
import static aps.Descriptografia.ordemPuzzle;
import javax.swing.ImageIcon;
/**
 *
 * @author UnGui
 */
public class TelaPuzzle extends javax.swing.JFrame {

    private boolean teste01;
    private boolean puzzle01;
    

    
    /**
     * Creates new form TelaPuzzle
     */
    public TelaPuzzle() {
        initComponents();     
        initComponents();
        ImageIcon imageLbl = new ImageIcon("src/aps/image/lousa.png");
        imageLbl.setImage(imageLbl.getImage().getScaledInstance(430, 300, 1));
        lblImage.setIcon(imageLbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupBtnAlternative = new javax.swing.ButtonGroup();
        Alternativa01 = new javax.swing.JRadioButton();
        Alternativa02 = new javax.swing.JRadioButton();
        Alternativa03 = new javax.swing.JRadioButton();
        Alternativa04 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_tituloQuest = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        groupBtnAlternative.add(Alternativa01);
        Alternativa01.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Alternativa01.setForeground(new java.awt.Color(255, 255, 255));
        Alternativa01.setOpaque(false);
        Alternativa01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alternativa01ActionPerformed(evt);
            }
        });
        getContentPane().add(Alternativa01);
        Alternativa01.setBounds(54, 136, 60, 20);

        groupBtnAlternative.add(Alternativa02);
        Alternativa02.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Alternativa02.setForeground(new java.awt.Color(255, 255, 255));
        Alternativa02.setOpaque(false);
        Alternativa02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alternativa02ActionPerformed(evt);
            }
        });
        getContentPane().add(Alternativa02);
        Alternativa02.setBounds(54, 193, 60, 20);

        groupBtnAlternative.add(Alternativa03);
        Alternativa03.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Alternativa03.setForeground(new java.awt.Color(255, 255, 255));
        Alternativa03.setOpaque(false);
        Alternativa03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alternativa03ActionPerformed(evt);
            }
        });
        getContentPane().add(Alternativa03);
        Alternativa03.setBounds(317, 136, 70, 20);

        groupBtnAlternative.add(Alternativa04);
        Alternativa04.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Alternativa04.setForeground(new java.awt.Color(255, 255, 255));
        Alternativa04.setOpaque(false);
        Alternativa04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alternativa04ActionPerformed(evt);
            }
        });
        getContentPane().add(Alternativa04);
        Alternativa04.setBounds(317, 193, 70, 20);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 0, 250, 40);

        lbl_tituloQuest.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lbl_tituloQuest.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tituloQuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_tituloQuest);
        lbl_tituloQuest.setBounds(54, 46, 322, 33);
        getContentPane().add(lblImage);
        lblImage.setBounds(0, 0, 430, 300);

        setSize(new java.awt.Dimension(430, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        switch (ordemPuzzle) {
            case 0:
                lbl_tituloQuest.setText("2 + 2 = ?");
                Alternativa01.setText("1");
                Alternativa02.setText("3");
                Alternativa03.setText("4");
                Alternativa04.setText("22");
                break;
            case 1:
                lbl_tituloQuest.setText("7 + 4 = ?");
                Alternativa01.setText("9");
                Alternativa02.setText("11");
                Alternativa03.setText("74");
                Alternativa04.setText("13");
                break;
            case 2:
                lbl_tituloQuest.setText("5 x 7 = ?");
                Alternativa01.setText("35");
                Alternativa02.setText("25");
                Alternativa03.setText("25");
                Alternativa04.setText("30");
                break;
            case 3:
                lbl_tituloQuest.setText("24 / 8 = ?");
                Alternativa01.setText("2");
                Alternativa02.setText("3");
                Alternativa03.setText("4");
                Alternativa04.setText("8");
                break;
            case 4:
                lbl_tituloQuest.setText("37 - 28 = ?");
                Alternativa01.setText("12");
                Alternativa02.setText("9");
                Alternativa03.setText("11");
                Alternativa04.setText("8");
                break;
            case 5:
                lbl_tituloQuest.setText("50 - 10 = ?");
                Alternativa01.setText("50");
                Alternativa02.setText("20");
                Alternativa03.setText("10");
                Alternativa04.setText("40");
                break;    
        }
    }//GEN-LAST:event_formWindowActivated

    private void Alternativa01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alternativa01ActionPerformed
        // TODO add your handling code here:
        switch (ordemPuzzle) {
            case 0:       
                acerto = false;                    
                this.setVisible(false);
                break;
            case 1:
                acerto = false;                    
                this.setVisible(false);
                break;
            case 2:
                acerto = true;                    
                this.setVisible(false);
                break;
            case 3:
                acerto = false;                    
                this.setVisible(false);
                break;
            case 4:
                acerto = false;                    
                this.setVisible(false);
                break;
            case 5:
                acerto = false;                    
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_Alternativa01ActionPerformed

    private void Alternativa02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alternativa02ActionPerformed
        // TODO add your handling code here:
        switch (ordemPuzzle) {
            case 0:       
                acerto = false;                    
                this.setVisible(false);
                break;
            case 1:
                acerto = true;                    
                this.setVisible(false);
                break;
            case 2:
                acerto = false;                    
                this.setVisible(false);
                break;
            case 3:
                acerto = true;                    
                this.setVisible(false);
                break;
            case 4:
                acerto = false;                    
                this.setVisible(false);
                break;
            case 5:
                acerto = false;                    
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_Alternativa02ActionPerformed

    private void Alternativa03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alternativa03ActionPerformed
        // TODO add your handling code here:
        switch (ordemPuzzle) {
            case 0:       
                acerto = true;                    
                this.setVisible(false);
                break;
            case 1:
                acerto = false;                    
                this.setVisible(false);
                break;
            case 2:
                acerto = false;                    
                this.setVisible(false);
                break;
            case 3:
                acerto = false;                    
                this.setVisible(false);
                break;
            case 4:
                acerto = false;                    
                this.setVisible(false);
                break;
            case 5:
                acerto = false;                    
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_Alternativa03ActionPerformed

    private void Alternativa04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alternativa04ActionPerformed
        // TODO add your handling code here:
        switch (ordemPuzzle) {
            case 0:       
                acerto = false;                    
                this.setVisible(false);
                break;
            case 1:
                acerto = false;                    
                this.setVisible(false);
                break;
            case 2:
                acerto = false;                    
                this.setVisible(false);
                break;
            case 3:
                acerto = false;                    
                this.setVisible(false);
                break;
            case 4:
                acerto = false;                    
                this.setVisible(false);
                break;
            case 5:
                acerto = true;                    
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_Alternativa04ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPuzzle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Alternativa01;
    private javax.swing.JRadioButton Alternativa02;
    private javax.swing.JRadioButton Alternativa03;
    private javax.swing.JRadioButton Alternativa04;
    private javax.swing.ButtonGroup groupBtnAlternative;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lbl_tituloQuest;
    // End of variables declaration//GEN-END:variables
}
