package aps;

import static aps.TelaInicial.profileURL;
import static aps.TelaInicial.nameUser;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author UnGui
 */
public class TelaNewUser extends javax.swing.JFrame {

    /**
     * Creates new form TelaNewUser
     */

            
    public TelaNewUser() {
        initComponents();
        //Tela Full Screen
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        barraFerramenta = new javax.swing.JPanel();
        EventClicked__ShutDown = new javax.swing.JLabel();
        icon__shutDown = new javax.swing.JLabel();
        lbl__Desligar = new javax.swing.JLabel();
        jPanel__principal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        input__nome = new javax.swing.JTextField();
        icon__userNew = new javax.swing.JLabel();
        lbl__nome = new javax.swing.JLabel();
        lbl__nome1 = new javax.swing.JLabel();
        btn__salvar = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        blackground__NewUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1365, 785));
        setSize(new java.awt.Dimension(1365, 785));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(148, 186, 67));
        jPanel1.setPreferredSize(new java.awt.Dimension(1365, 70));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aps/image/newIcon__plantLogo.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 0, 80, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1365, 80);

        barraFerramenta.setBackground(new java.awt.Color(148, 186, 67));
        barraFerramenta.setPreferredSize(new java.awt.Dimension(1365, 70));
        barraFerramenta.setLayout(null);

        EventClicked__ShutDown.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EventClicked__ShutDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EventClicked__ShutDownMouseClicked(evt);
            }
        });
        barraFerramenta.add(EventClicked__ShutDown);
        EventClicked__ShutDown.setBounds(100, 10, 180, 50);

        icon__shutDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aps/image/icon__desligar_1.png"))); // NOI18N
        icon__shutDown.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraFerramenta.add(icon__shutDown);
        icon__shutDown.setBounds(110, 15, 38, 40);

        lbl__Desligar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lbl__Desligar.setForeground(new java.awt.Color(255, 255, 255));
        lbl__Desligar.setText("Desligar");
        barraFerramenta.add(lbl__Desligar);
        lbl__Desligar.setBounds(160, 15, 190, 42);

        getContentPane().add(barraFerramenta);
        barraFerramenta.setBounds(0, 700, 1365, 70);

        jPanel__principal.setBackground(new java.awt.Color(241, 241, 241));
        jPanel__principal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(116, 170, 67), 5));
        jPanel__principal.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(168, 183, 95));
        jLabel3.setText("Como podemos te chamar?");
        jPanel__principal.add(jLabel3);
        jLabel3.setBounds(80, 40, 380, 31);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 9)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("<html>\nAo se registrar, você concorda com os <strong style=\"color:#A8B75F\"> termos de serviços </strong> e a <strong style=\"color:#A8B75F\"> política de privacidade </strong> .\n</html>");
        jPanel__principal.add(jLabel4);
        jLabel4.setBounds(40, 340, 450, 40);

        input__nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        input__nome.setForeground(new java.awt.Color(51, 51, 51));
        jPanel__principal.add(input__nome);
        input__nome.setBounds(200, 180, 280, 40);

        icon__userNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aps/image/NewIcon__UserNewCinza.png"))); // NOI18N
        icon__userNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon__userNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon__userNewMouseClicked(evt);
            }
        });
        jPanel__principal.add(icon__userNew);
        icon__userNew.setBounds(30, 120, 150, 150);

        lbl__nome.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        lbl__nome.setForeground(new java.awt.Color(153, 153, 153));
        lbl__nome.setText("Digite como desejar ser chamado");
        jPanel__principal.add(lbl__nome);
        lbl__nome.setBounds(200, 220, 170, 13);

        lbl__nome1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lbl__nome1.setForeground(new java.awt.Color(153, 153, 153));
        lbl__nome1.setText("Nome / Apelido");
        jPanel__principal.add(lbl__nome1);
        lbl__nome1.setBounds(200, 140, 200, 29);

        btn__salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aps/image/newIcon__btn.png"))); // NOI18N
        btn__salvar.setText("jLabel1");
        btn__salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn__salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn__salvarMouseClicked(evt);
            }
        });
        jPanel__principal.add(btn__salvar);
        btn__salvar.setBounds(370, 280, 110, 40);

        getContentPane().add(jPanel__principal);
        jPanel__principal.setBounds(400, 160, 530, 380);

        jPanel6.setBackground(new java.awt.Color(58, 121, 18));
        jPanel6.setPreferredSize(new java.awt.Dimension(4, 240));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(735, 120, 240, 5);

        jPanel7.setBackground(new java.awt.Color(58, 121, 18));
        jPanel7.setPreferredSize(new java.awt.Dimension(4, 240));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7);
        jPanel7.setBounds(970, 125, 5, 240);

        jPanel5.setBackground(new java.awt.Color(58, 121, 18));
        jPanel5.setPreferredSize(new java.awt.Dimension(4, 240));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(365, 575, 240, 5);

        jPanel4.setBackground(new java.awt.Color(58, 121, 18));
        jPanel4.setPreferredSize(new java.awt.Dimension(4, 240));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(360, 340, 5, 240);
        getContentPane().add(blackground__NewUser);
        blackground__NewUser.setBounds(0, 50, 1365, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Começo BackGround
        ImageIcon background = new ImageIcon("src/aps/image/background__Inicial.png");
        background.setImage(background.getImage().getScaledInstance(1365 ,900, 1));
        blackground__NewUser.setIcon(background);
        //Fim BackGround
    }//GEN-LAST:event_formWindowOpened

    private void btn__salvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn__salvarMouseClicked
        // TODO add your handling code here:
        nameUser = input__nome.getText();
        this.setVisible(false);
        new TelaDesktop().setVisible(true);       
    }//GEN-LAST:event_btn__salvarMouseClicked

    //Label invisible que irá possibilitar ao clickar o efeito de Exit
    private void EventClicked__ShutDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EventClicked__ShutDownMouseClicked
        //Icon Desligar => iconShutDown
        ImageIcon iconShutDown = new ImageIcon("src/aps/image/icon__desligar_1.png");            
            //Perguntando ao usuário se realmente deseja sair do sistema 
            if (JOptionPane.showConfirmDialog(null,"Deseja Desligar ?","Desligamento",JOptionPane.OK_OPTION, JOptionPane.CANCEL_OPTION,iconShutDown) == JOptionPane.OK_OPTION)
                {
                    System.exit(0);
                }  
    }//GEN-LAST:event_EventClicked__ShutDownMouseClicked

    //Event Clicked, que irá abrir a janela de modificação foto de Perfil
    private void icon__userNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon__userNewMouseClicked
        
        new IconSettings().setVisible(true);
    }//GEN-LAST:event_icon__userNewMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        ClassMain dadosUsuario = new ClassMain(); 
//      Aqui estamos colocando o valor salvo na Variavel Global / TelaINICIAL
        ImageIcon newProfile = new ImageIcon(profileURL);
        //Modificando o Icon
        icon__userNew.setIcon(newProfile);
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EventClicked__ShutDown;
    private javax.swing.JPanel barraFerramenta;
    private javax.swing.JLabel blackground__NewUser;
    private javax.swing.JLabel btn__salvar;
    private javax.swing.JLabel icon__shutDown;
    public javax.swing.JLabel icon__userNew;
    private javax.swing.JTextField input__nome;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel__principal;
    private javax.swing.JLabel lbl__Desligar;
    private javax.swing.JLabel lbl__nome;
    public javax.swing.JLabel lbl__nome1;
    // End of variables declaration//GEN-END:variables
}
