/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aps;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author UnGui
 */
public class TelaNewUser extends javax.swing.JFrame {

    /**
     * Creates new form TelaNewUser
     */
    public TelaNewUser() {
        initComponents();
        //Tela Full Screen
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barraFerramenta = new javax.swing.JPanel();
        icon__shutDown = new javax.swing.JLabel();
        lbl__Desligar = new javax.swing.JLabel();
        jPanel__principal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        input1 = new javax.swing.JTextField();
        icon__userNew = new javax.swing.JLabel();
        lbl__nome = new javax.swing.JLabel();
        btn__salvar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        blackground__NewUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1365, 785));
        setSize(new java.awt.Dimension(1365, 785));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(148, 186, 67));
        jPanel1.setPreferredSize(new java.awt.Dimension(1365, 70));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1365, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1365, 70);

        barraFerramenta.setBackground(new java.awt.Color(148, 186, 67));
        barraFerramenta.setPreferredSize(new java.awt.Dimension(1365, 70));
        barraFerramenta.setLayout(null);

        icon__shutDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aps/image/icon__desligar_1.png"))); // NOI18N
        barraFerramenta.add(icon__shutDown);
        icon__shutDown.setBounds(110, 15, 38, 40);

        lbl__Desligar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lbl__Desligar.setForeground(new java.awt.Color(255, 255, 255));
        lbl__Desligar.setText("Desligar");
        barraFerramenta.add(lbl__Desligar);
        lbl__Desligar.setBounds(160, 15, 190, 42);

        getContentPane().add(barraFerramenta);
        barraFerramenta.setBounds(0, 680, 1365, 70);

        jPanel__principal.setBackground(new java.awt.Color(241, 241, 241));
        jPanel__principal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(116, 170, 67), 4));
        jPanel__principal.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(168, 183, 95));
        jLabel3.setText("Como podemos te chamar?");
        jPanel__principal.add(jLabel3);
        jLabel3.setBounds(80, 40, 380, 31);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Ao se registrar, você concorda com os termos de serviços e a política de privacidade .");
        jPanel__principal.add(jLabel4);
        jLabel4.setBounds(10, 340, 520, 40);

        input1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        input1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel__principal.add(input1);
        input1.setBounds(170, 160, 280, 40);

        icon__userNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aps/image/icon__userNewUser.png"))); // NOI18N
        jPanel__principal.add(icon__userNew);
        icon__userNew.setBounds(30, 110, 100, 100);

        lbl__nome.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lbl__nome.setText("Nome / Apelido");
        jPanel__principal.add(lbl__nome);
        lbl__nome.setBounds(170, 120, 200, 29);

        btn__salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aps/image/icon__buttonSalvar.png"))); // NOI18N
        btn__salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn__salvarMouseClicked(evt);
            }
        });
        jPanel__principal.add(btn__salvar);
        btn__salvar.setBounds(170, 260, 190, 50);

        getContentPane().add(jPanel__principal);
        jPanel__principal.setBounds(400, 160, 530, 380);

        jPanel6.setBackground(new java.awt.Color(58, 97, 25));
        jPanel6.setPreferredSize(new java.awt.Dimension(4, 240));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(735, 120, 240, 5);

        jPanel7.setBackground(new java.awt.Color(58, 97, 25));
        jPanel7.setPreferredSize(new java.awt.Dimension(4, 240));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7);
        jPanel7.setBounds(970, 125, 5, 240);

        jPanel5.setBackground(new java.awt.Color(58, 97, 25));
        jPanel5.setPreferredSize(new java.awt.Dimension(4, 240));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(365, 575, 240, 5);

        jPanel4.setBackground(new java.awt.Color(58, 97, 25));
        jPanel4.setPreferredSize(new java.awt.Dimension(4, 240));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(360, 340, 5, 240);
        getContentPane().add(blackground__NewUser);
        blackground__NewUser.setBounds(0, 50, 1365, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //Começo BackGround
        ImageIcon background = new ImageIcon("src/aps/image/background__Inicial.png");
        background.setImage(background.getImage().getScaledInstance(1365 ,900, 1));
        blackground__NewUser.setIcon(background);
        //Fim BackGround
    }//GEN-LAST:event_formWindowOpened

    private void btn__salvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn__salvarMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new TelaCapitulos().setVisible(true);
    }//GEN-LAST:event_btn__salvarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraFerramenta;
    private javax.swing.JLabel blackground__NewUser;
    private javax.swing.JButton btn__salvar;
    private javax.swing.JLabel icon__shutDown;
    private javax.swing.JLabel icon__userNew;
    private javax.swing.JTextField input1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel__principal;
    private javax.swing.JLabel lbl__Desligar;
    private javax.swing.JLabel lbl__nome;
    // End of variables declaration//GEN-END:variables
}
