/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aps;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author UnGui
 */
public class TelaDesktop extends javax.swing.JFrame {

    /**
     * Creates new form TelaDesktop
     */
    public TelaDesktop() {
        initComponents();
        //Tela Full Screen
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraFerramenta = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        barraFerramenta__UserConfig = new javax.swing.JPanel();
        user__config = new javax.swing.JLabel();
        barraFerramenta__nomeMensagger = new javax.swing.JPanel();
        barraFerramenta__Hour = new javax.swing.JPanel();
        hour = new javax.swing.JLabel();
        icon__Mensegger = new javax.swing.JLabel();
        icon__puzzle = new javax.swing.JLabel();
        background__Desktop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1365, 785));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        barraFerramenta.setBackground(new java.awt.Color(148, 186, 67));
        barraFerramenta.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(148, 186, 67));
        jPanel2.setLayout(null);
        barraFerramenta.add(jPanel2);
        jPanel2.setBounds(0, 590, 1365, 50);

        barraFerramenta__UserConfig.setBackground(new java.awt.Color(168, 183, 95));

        user__config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aps/image/icon__userConfig.png"))); // NOI18N

        javax.swing.GroupLayout barraFerramenta__UserConfigLayout = new javax.swing.GroupLayout(barraFerramenta__UserConfig);
        barraFerramenta__UserConfig.setLayout(barraFerramenta__UserConfigLayout);
        barraFerramenta__UserConfigLayout.setHorizontalGroup(
            barraFerramenta__UserConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraFerramenta__UserConfigLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(user__config, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        barraFerramenta__UserConfigLayout.setVerticalGroup(
            barraFerramenta__UserConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraFerramenta__UserConfigLayout.createSequentialGroup()
                .addComponent(user__config, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        barraFerramenta.add(barraFerramenta__UserConfig);
        barraFerramenta__UserConfig.setBounds(0, 0, 80, 60);

        barraFerramenta__nomeMensagger.setBackground(new java.awt.Color(168, 183, 95));

        javax.swing.GroupLayout barraFerramenta__nomeMensaggerLayout = new javax.swing.GroupLayout(barraFerramenta__nomeMensagger);
        barraFerramenta__nomeMensagger.setLayout(barraFerramenta__nomeMensaggerLayout);
        barraFerramenta__nomeMensaggerLayout.setHorizontalGroup(
            barraFerramenta__nomeMensaggerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        barraFerramenta__nomeMensaggerLayout.setVerticalGroup(
            barraFerramenta__nomeMensaggerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        barraFerramenta.add(barraFerramenta__nomeMensagger);
        barraFerramenta__nomeMensagger.setBounds(120, 0, 200, 50);

        barraFerramenta__Hour.setBackground(new java.awt.Color(168, 183, 95));
        barraFerramenta__Hour.setLayout(null);

        hour.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        hour.setForeground(new java.awt.Color(255, 255, 255));
        hour.setText("17:20");
        barraFerramenta__Hour.add(hour);
        hour.setBounds(10, 6, 64, 29);

        barraFerramenta.add(barraFerramenta__Hour);
        barraFerramenta__Hour.setBounds(1280, 0, 90, 50);

        getContentPane().add(barraFerramenta);
        barraFerramenta.setBounds(0, 700, 1365, 50);

        icon__Mensegger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aps/image/icon__mensager.png"))); // NOI18N
        getContentPane().add(icon__Mensegger);
        icon__Mensegger.setBounds(30, 30, 50, 60);

        icon__puzzle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aps/image/icon__puzzle.png"))); // NOI18N
        getContentPane().add(icon__puzzle);
        icon__puzzle.setBounds(30, 110, 50, 60);
        getContentPane().add(background__Desktop);
        background__Desktop.setBounds(0, 0, 1365, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //Começo BackGround
        ImageIcon background = new ImageIcon("src/aps/image/wallpaper.png");
        background.setImage(background.getImage().getScaledInstance(1365 ,900, 1));
        background__Desktop.setIcon(background);
        //Fim BackGround
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDesktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background__Desktop;
    private javax.swing.JPanel barraFerramenta;
    private javax.swing.JPanel barraFerramenta__Hour;
    private javax.swing.JPanel barraFerramenta__UserConfig;
    private javax.swing.JPanel barraFerramenta__nomeMensagger;
    private javax.swing.JLabel hour;
    private javax.swing.JLabel icon__Mensegger;
    private javax.swing.JLabel icon__puzzle;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel user__config;
    // End of variables declaration//GEN-END:variables
}
