/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aps;
import static aps.DescriptografandoAndEnviando.acerto;
import static aps.DescriptografandoAndEnviando.ordemPuzzle;
/**
 *
 * @author UnGui
 */
public class TelaPuzzle extends javax.swing.JFrame {

    private boolean teste01;
    private boolean puzzle01;
    

    
    /**
     * Creates new form TelaPuzzle
     */
    public TelaPuzzle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        Alternativa01 = new javax.swing.JRadioButton();
        Alternativa02 = new javax.swing.JRadioButton();
        Alternativa03 = new javax.swing.JRadioButton();
        Alternativa04 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_tituloQuest = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("RESPONDE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Alternativa01);
        Alternativa01.setText("true");

        buttonGroup1.add(Alternativa02);
        Alternativa02.setText("true");

        buttonGroup1.add(Alternativa03);
        Alternativa03.setText("false");

        buttonGroup1.add(Alternativa04);
        Alternativa04.setText("false");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("0 %");

        lbl_tituloQuest.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Alternativa02)
                    .addComponent(Alternativa01))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Alternativa03)
                    .addComponent(Alternativa04))
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lbl_tituloQuest, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbl_tituloQuest, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alternativa01)
                    .addComponent(Alternativa03))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alternativa02)
                    .addComponent(Alternativa04))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            DescriptografandoAndEnviando Descriptografia = new DescriptografandoAndEnviando();
        if (Alternativa01.isSelected()){            
            acerto = true;
        }else if (Alternativa02.isSelected()){
            acerto = true;    
        }else if (Alternativa03.isSelected()){
            acerto = false;   
        }else if (Alternativa04.isSelected()){
            acerto = false;    
        }
//        System.out.println(acerto);
//        if (acerto == false) {//Usuário Errou
//            Descriptografia.seconds -= 24; //Para fica visivel ao usuário a perca de 30
//            Descriptografia.jProgressBar1.setValue(-24);
//            System.out.println("cai aqui no acerto false");
//            Descriptografia.fracassou += 1;
//        }
//        System.out.println(Descriptografia.jProgressBar1.getValue());
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        switch (ordemPuzzle) {
            case 0:
                Alternativa01.setText("0");
                Alternativa02.setText("0");
                Alternativa03.setText("0");
                Alternativa04.setText("0");
                break;
            case 1:
                Alternativa01.setText("1");
                Alternativa02.setText("1");
                Alternativa03.setText("1");
                Alternativa04.setText("1");
                break;
            case 2:
                Alternativa01.setText("2");
                Alternativa02.setText("2");
                Alternativa03.setText("2");
                Alternativa04.setText("2");
                break;
            case 3:
                Alternativa01.setText("3");
                Alternativa02.setText("3");
                Alternativa03.setText("3");
                Alternativa04.setText("3");
                break;
            case 4:
                Alternativa01.setText("4");
                Alternativa01.setText("4");
                Alternativa01.setText("4");
                Alternativa01.setText("4");
                break;
            case 5:
                Alternativa01.setText("5");
                Alternativa01.setText("5");
                Alternativa01.setText("5");
                Alternativa01.setText("5");
                break;    
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPuzzle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Alternativa01;
    private javax.swing.JRadioButton Alternativa02;
    private javax.swing.JRadioButton Alternativa03;
    private javax.swing.JRadioButton Alternativa04;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_tituloQuest;
    // End of variables declaration//GEN-END:variables
}
